### ISSUE TITLE
Makefile is not compatible with newer versions of sigs.k8s.io/controller-tools

### ISSUE THREAD

**Issue by csfreak** [fennec-project/snoopy-operator#43]
https://github.com/fennec-project/snoopy-operator/blob/56a283ba42e90bea9aa12e5f16639645208fb8bc/Makefile#L41

both of the options referenced here are removed in v0.7 of sigs.k8s.io/controller-tools as they are only used in v1beta1 crds,  which are removed as of k8s 1.22

Since the version of sigs.k8s.io/controller-tools isn't pinned to a pre-v0.7 version, new builds in clean environments fail.

**Comment by csfreak** [comment]
seems the line should be changed to 
`CRD_OPTIONS ?= "crd"`

**Comment by acmenezes** [comment]
Hi @csfreak , that makes total sense. I swapped this file recently and changed the CRDs from v1beta1 to v1 but I think I've introduced other problems. Another dev told me about that problem last week. Weirdly, it doesn't break on my environment. I'm putting this on the agenda for tomorrow's meeting.

**Comment by csfreak** [comment]
introduced in #38
