### ISSUE TITLE
ADD a cleanup strategy for completed jobs and cronJobs

### ISSUE THREAD

**Issue by acmenezes** [fennec-project/snoopy-operator#46]
Since Jobs and CronJobs are owned by the operator they may never be cleaned up from the output of the command  `oc get jobs` or `oc get cronjobs`. One way to think about this is:
- [ ] after having the jobs registered in the status field, we can initially have creating, running and completed
- [ ] we can define a field on the CRD to control for how long we are going to keep those jobs in the history if the CR itself is not deleted.

**Comment by tokalevasant** [comment]
**We can cleanp jobs by setting a ttl.** ex. 

_apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never_

**Comment by tokalevasant** [comment]
From oc explain 'job.spec'

ttlSecondsAfterFinished	<integer>
     ttlSecondsAfterFinished limits the lifetime of a Job that has finished
     execution (either Complete or Failed). If this field is set,
     ttlSecondsAfterFinished after the Job finishes, it is eligible to be
     automatically deleted. When the Job is being deleted, its lifecycle
     guarantees (e.g. finalizers) will be honored. If this field is unset, the
     Job won't be automatically deleted. If this field is set to zero, the Job
     becomes eligible to be deleted immediately after it finishes. This field is
     alpha-level and is only honored by servers that enable the TTLAfterFinished
     feature.

**Comment by acmenezes** [comment]
Hi @tokalevasant , cool! Thanks for checking it out. I think it can be used for the clean up part. Then what we still need to do is make the operator aware of this. I don't know if when the job is automatically deleted if the operator will trigger the reconciler and try to recreate the job. It seems interesting to have a check on the status field of the newly created CR that says that the jobs were initiated. Even if they failed or didn't complete yet. That would let the operator aware that that CR was initiated before. But I think it's for the issue #45 not for this one. I'm going to close this one then. Thanks again!
