### ISSUE TITLE
scc privileged not found

### ISSUE THREAD

**Issue by yuriolisa** [fennec-project/snoopy-operator#59]
I'm facing two issues during the first deployment of snoopy operator: 

- It's necessary to label a target node with `management=true`.
- scc-privileged not found as we can see in the error below: 

````
snoopy-operator-7b47d6f7b9-5fqc7 snoopy-operator E0221 10:01:42.307947       1 
leaderelection.go:330] error retrieving resource lock snoopy-operator/d86c1e11.fennecproject.io:
configmaps "d86c1e11.fennecproject.io" is forbidden: User "system:serviceaccount:snoopy
operator:snoopy-operator-sa" cannot get resource "configmaps" in API group "" in the namespace
"snoopy-operator": RBAC: role.rbac.authorization.k8s.io "role-scc-privileged" not found
````

**Comment by csfreak** [comment]
There are yaml files in config/rbac/samples/rbac_snoopy_operator_dev to resolve that,  There is lots of cleanup to do on the various yaml files in the repo

**Comment by acmenezes** [comment]
Hi guys, just opened the issue #60 to take care of those caveats. I'll be checking permissions and the makefile to make sure the install runs smoothly on a brand new OCP cluster. So I'm closing this one to work on a permanent solution for those issues.
