### ISSUE TITLE
Permission error deploying on OpenShift

### ISSUE THREAD

**Issue by tele0x** [fennec-project/snoopy-operator#8]
See below error on the snoopy-operator:

```
# oc logs -f pod/snoopy-operator-76fb4d998b-m4xf5 -n snoopy-operator
E0806 13:18:19.646775       1 leaderelection.go:325] error retrieving resource lock snoopy-operator/d86c1e11.fennecproject.io: configmaps "d86c1e11.fennecproject.io" is forbidden: User "system:serviceaccount:snoopy-operator:snoopy-operator-sa" cannot get resource "configmaps" in API group "" in the namespace "snoopy-operator"
```

**Comment by acmenezes** [comment]
Hi @tele0x I wasn't able to reproduce the error. Can describe exactly what steps you took and what is your OCP version/environment?

**Comment by tele0x** [comment]
Tried to deploy on two clusters. I am using admin (cluster-admin) user, followed instructions, applied deployment manifests tagged the nodes then did the `make deploy`. The operator pod is up and running and also the pods under cnf-telco.

```
$ oc get pods -n snoopy-operator
NAME                              READY   STATUS    RESTARTS   AGE
snoopy-operator-cd84cdf8b-vnp8m   1/1     Running   0          8m9s
$ oc get pods -n cnf-telco
NAME                              READY   STATUS    RESTARTS   AGE
cnf-example-pod-98b9d4df8-cd2ch   1/1     Running   0          10m
cnf-example-pod-98b9d4df8-fkgkb   1/1     Running   0          10m
```

CLUSTER A
```
$ oc version
Client Version: 4.8.3
Server Version: 4.8.2
Kubernetes Version: v1.21.1+051ac4f
```

CLUSTER B
```
# oc version
Client Version: 4.7.0
Server Version: 4.7.0
Kubernetes Version: v1.20.0+bd9e442
```

when I try to apply the following manifest

```yaml
apiVersion: pcap.fennecproject.io/v1alpha1
kind: Tcpdump
metadata:
  name: tcpdump-sample
spec:
  name: test-pcap
  targetNamespace: cnf-telco
  podLabel: { 
    app: 5gcore
    }
  interfaceName: eth0
  packetCount: 10000
```

No tcpdump pods are created. The tcpdump crd does exist.

**Comment by acmenezes** [comment]
Did you applied this manifest in the cnf-telco namespace? With oc apply -f <file name> -n cnf-telco? I guess that may be the problem.

**Comment by tele0x** [comment]
Upgraded my cluster to 4.8.4 and without changing anything is now working no more errors on the pod. Yes, manifests were applied with the namespace `cnf-telco` and `config/samples/sample-deployment.yaml` already has the `cnf-telco` namespace defined too. I'll see if I can reproduce on another cluster but for now all good.

**Comment by acmenezes** [comment]
Interesting. Thanks for this update! Cluster version shouldn't be an issue though. If you find any other issue please let me know. Any feature request is also welcome.
